config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :cars
    # TODO: read about nesting routes 'articles'
  end

  resources :cars, only: [:index, :show]
  namespace :admin do
    resources :articles
  end
  resources :articles, only: [:show]

  root 'cars#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :car
  validates :title, :body, presence: true

  def bodyshow
    [self.title, self.body].join(' ')
  end

end

app/models/car.rb
class Car < ApplicationRecord
  validates :year, :manufacture, :model, presence: true
  
  def full_name
    [self.year, self.manufacture, self.model].join(' ')
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController

  def show
    @article = Articles.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_article_path(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to admin_car_path(@car), notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to admin_car_path(@car), notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @car.destroy
    redirect_to admin_cars_url, notice: 'Car was successfully destroyed.'
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:manufacture, :model, :year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Articles.find(params[:id])
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for([:admin, article]) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :article_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/new.html.erb
<h1>New Admin Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/cars/_form.html.erb
<%= form_for([:admin, car]) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :manufacture %>
    <%= form.text_field :manufacture, id: :car_manufacture %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :car_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/cars/edit.html.erb
<h1>Editing Admin Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', admin_cars_path %>

app/views/admin/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Cars</h1>

<table>
  <thead>
    <tr>
      <th>Manufacture</th>
      <th>Model</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.manufacture %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= link_to 'Show', admin_car_path(car) %></td>
        <td><%= link_to 'Edit', edit_admin_car_path(car) %></td>
        <td><%= link_to 'Destroy', admin_car_path(car), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Car', new_admin_car_path %>

app/views/admin/cars/new.html.erb
<h1>New Admin Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', admin_cars_path %>

app/views/admin/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manufacture:</strong>
  <%= @car.manufacture %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<%= link_to 'Edit', edit_admin_car_path(@car) %> |
<%= link_to 'Back', admin_cars_path %>

app/views/articles/show.slim
h2
  = @article.bodyshow

app/views/cars/index.slim
h2
  |
    Cars
ul
  - @cars.each do |c|
    li= c.model

app/views/cars/show.slim
h1
  = @car.full_name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>